### ISSUE TITLE
Implementing drive_model file in ipython

### ISSUE THREAD

**Issue by omerqureshi84** [Intenzo21/Brain-Inspired-Deep-Imitation-Learning-for-Autonomous-Driving-Systems#1]
I have already run the file of constants in ipython and now trying to run the drive_model file but it is giving me the following error:

usage: [-h] model [speed] [image_folder]
: error: the following arguments are required: model
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

How can i solve this?

**Comment by Intenzo21** [comment]
You must specify a pretrained model path as a command-line argument. Please try this out and let me know if the issue persists.

**Comment by omerqureshi84** [comment]
I ran the below mentioned line on my command prompt and then executed the udacity simulator and pressed the autonomous driving button:

C:\Users\Acer\Desktop\code for brain ispired\udacity>python drive_model.py cnn_model-0.009425.h5 25 cnn_run

The result of code:

Creating image folder at cnn_run
RECORDING THIS RUN ...
(15052) wsgi starting up on http://0.0.0.0:4567
(15052) accepted ('127.0.0.1', 58982)

The above code has been running some over 20 hours now and nothing happens next. Am I doing something wrong here?

**Comment by Intenzo21** [comment]
Are you using the right package versions as mentioned in the maintenance manual?

Specifically, the crucial ones to run the simulator are Keras and Tensorflow versions.

Please make sure you have the right ones installed since the models have been trained using these versions.

If you have the right versions and the problem is still unresolved then you could try to run a different model first.

**Comment by omerqureshi84** [comment]
Ok. I managed to run the drive_model.py file. There was a problem with the versions I had installed on my system. 

Now I want to replicate figures 4 and 5 in the paper. I ran the following code on the command line for udacity dataset:

C:\Users\Acer\Desktop\code for brain ispired\udacity>python train_model.py cnn

After running the above code, I get the error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Acer/Desktop/code for brain ispired/udacity/lakeside_map/IMG\\center_2019_04_02_18_14_16_791.jpg'

I checked the folder of lakeside_map and there are no files starting with center_2019.

Is there something I am doing wrong?
